"""add tbl_user_application

Revision ID: 281e735b810c
Revises: 10db59f8cbaf
Create Date: 2025-12-30 09:21:27.834436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281e735b810c'
down_revision: Union[str, Sequence[str], None] = '10db59f8cbaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_user_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, server_default="ACTIVE"),
    sa.ForeignKeyConstraint(['application_id'], ['tbl_application.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'application_id', name='uq_user_application')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_application')
    # ### end Alembic commands ###
