"""extend audit_log for middleware

Revision ID: b1b97438ffd3
Revises: ce811eefb2ec
Create Date: 2026-01-06 13:49:08.514174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1b97438ffd3'
down_revision: Union[str, Sequence[str], None] = 'ce811eefb2ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('app_code', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tbl_audit_log', sa.Column('method', sa.String(length=10), nullable=True))
    op.add_column('tbl_audit_log', sa.Column('path', sa.String(length=255), nullable=True))
    op.add_column('tbl_audit_log', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('tbl_audit_log', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('tbl_audit_log', sa.Column('extra', sa.Text(), nullable=True))
    op.alter_column('tbl_audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_audit_log', 'resource',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('tbl_audit_log', 'extra')
    op.drop_column('tbl_audit_log', 'duration_ms')
    op.drop_column('tbl_audit_log', 'status_code')
    op.drop_column('tbl_audit_log', 'path')
    op.drop_column('tbl_audit_log', 'method')
    op.drop_table('tbl_request_log')
    # ### end Alembic commands ###
